# Generated by Django 2.1 on 2020-05-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500)),
                ('public_title', models.CharField(max_length=500)),
                ('public_keywords', models.CharField(max_length=1000)),
                ('public_description', models.CharField(max_length=1000)),
                ('public_image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Drafted for future editing'), ('published', 'Published for the public preview'), ('deleted', 'Soft deleted')], max_length=100)),
            ],
        ),
    ]
