# Generated by Django 2.1 on 2020-05-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200520_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('drafted', 'Draft for future editing'), ('published', 'Publish for the public preview'), ('deleted', 'Soft delete')], default=0, max_length=100),
        ),
    ]
