# Generated by Django 2.1 on 2020-05-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200522_0720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox',
            options={'verbose_name_plural': 'Inbox'},
        ),
    ]
