# Generated by Django 2.1 on 2020-05-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200520_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='updated_at',
            new_name='last_updated',
        ),
    ]
