# Generated by Django 2.1 on 2020-05-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200520_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.CharField(default='1 min read', max_length=20),
        ),
    ]
