# Generated by Django 2.1 on 2020-05-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_article_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='page_url',
            new_name='page_name',
        ),
    ]
