# Generated by Django 2.1 on 2020-05-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200522_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
