# Generated by Django 2.1 on 2020-05-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200521_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='page_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
