# Generated by Django 2.1 on 2020-06-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200522_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('comments', models.TextField(max_length=2500)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SH', 'Show'), ('HD', 'Hide')], default='SH', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='page_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Article'),
        ),
    ]
