# Generated by Django 2.1 on 2020-06-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200601_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('linkedIn_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=3000)),
                ('joined_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default='AC', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Authors'),
        ),
    ]
