# Generated by Django 2.1 on 2020-06-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_authors_github_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', "Don't want to share")], default='N', max_length=1),
        ),
    ]
