# Generated by Django 2.1 on 2020-06-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_authors_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
