# Generated by Django 2.1 on 2020-06-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_authors_extra_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_maintenance', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'WebsiteSettings',
            },
        ),
    ]
