# Generated by Django 2.1 on 2020-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_websitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
